# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'holes_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HolesForm(object):
    def setupUi(self, HolesForm):
        HolesForm.setObjectName("HolesForm")
        HolesForm.resize(558, 452)
        self.StartButton = QtWidgets.QPushButton(HolesForm)
        self.StartButton.setGeometry(QtCore.QRect(170, 390, 221, 41))
        self.StartButton.setObjectName("StartButton")
        self.scrollArea = QtWidgets.QScrollArea(HolesForm)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(0, 10, 741, 381))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 739, 379))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LabelGroup = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.LabelGroup.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelGroup.sizePolicy().hasHeightForWidth())
        self.LabelGroup.setSizePolicy(sizePolicy)
        self.LabelGroup.setMinimumSize(QtCore.QSize(0, 50))
        self.LabelGroup.setTitle("")
        self.LabelGroup.setObjectName("LabelGroup")
        self.HoleLabel = QtWidgets.QLabel(self.LabelGroup)
        self.HoleLabel.setGeometry(QtCore.QRect(10, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.HoleLabel.setFont(font)
        self.HoleLabel.setObjectName("HoleLabel")
        self.HoleSizeLabel = QtWidgets.QLabel(self.LabelGroup)
        self.HoleSizeLabel.setGeometry(QtCore.QRect(200, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.HoleSizeLabel.setFont(font)
        self.HoleSizeLabel.setObjectName("HoleSizeLabel")
        self.BaseAddressLabel = QtWidgets.QLabel(self.LabelGroup)
        self.BaseAddressLabel.setGeometry(QtCore.QRect(70, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BaseAddressLabel.setFont(font)
        self.BaseAddressLabel.setObjectName("BaseAddressLabel")
        self.verticalLayout.addWidget(self.LabelGroup)
        self.HoleGroup = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HoleGroup.sizePolicy().hasHeightForWidth())
        self.HoleGroup.setSizePolicy(sizePolicy)
        self.HoleGroup.setMinimumSize(QtCore.QSize(0, 50))
        self.HoleGroup.setTitle("")
        self.HoleGroup.setObjectName("HoleGroup")
        self.HoleSizeSpin = QtWidgets.QSpinBox(self.HoleGroup)
        self.HoleSizeSpin.setGeometry(QtCore.QRect(200, 10, 101, 22))
        self.HoleSizeSpin.setObjectName("HoleSizeSpin")
        self.H1 = QtWidgets.QLabel(self.HoleGroup)
        self.H1.setGeometry(QtCore.QRect(-10, 0, 61, 31))
        self.H1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.H1.setAlignment(QtCore.Qt.AlignCenter)
        self.H1.setObjectName("H1")
        self.BaseAddressSpin = QtWidgets.QSpinBox(self.HoleGroup)
        self.BaseAddressSpin.setGeometry(QtCore.QRect(70, 10, 101, 22))
        self.BaseAddressSpin.setObjectName("BaseAddressSpin")
        self.verticalLayout.addWidget(self.HoleGroup)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(HolesForm)
        QtCore.QMetaObject.connectSlotsByName(HolesForm)

    def retranslateUi(self, HolesForm):
        _translate = QtCore.QCoreApplication.translate
        HolesForm.setWindowTitle(_translate("HolesForm", "Form"))
        self.StartButton.setText(_translate("HolesForm", "Start "))
        self.HoleLabel.setText(_translate("HolesForm", "Hole"))
        self.HoleSizeLabel.setText(_translate("HolesForm", "Size"))
        self.BaseAddressLabel.setText(_translate("HolesForm", "Base Address"))
        self.H1.setText(_translate("HolesForm", "H1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HolesForm = QtWidgets.QWidget()
    ui = Ui_HolesForm()
    ui.setupUi(HolesForm)
    HolesForm.show()
    sys.exit(app.exec_())
