# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'process.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(513, 473)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 50, 201, 21))
        self.label.setObjectName("label")
        self.radioGroup = QtWidgets.QGroupBox(Form)
        self.radioGroup.setGeometry(QtCore.QRect(40, 70, 231, 51))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.radioGroup.setFont(font)
        self.radioGroup.setTitle("")
        self.radioGroup.setObjectName("radioGroup")
        self.radioButton_3 = QtWidgets.QRadioButton(self.radioGroup)
        self.radioButton_3.setGeometry(QtCore.QRect(150, 20, 82, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton = QtWidgets.QRadioButton(self.radioGroup)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.radioGroup)
        self.radioButton_2.setGeometry(QtCore.QRect(80, 20, 82, 17))
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.SegmentTextBox = QtWidgets.QPlainTextEdit(Form)
        self.SegmentTextBox.setGeometry(QtCore.QRect(40, 200, 281, 161))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.SegmentTextBox.setFont(font)
        self.SegmentTextBox.setStatusTip("")
        self.SegmentTextBox.setPlainText("")
        self.SegmentTextBox.setObjectName("SegmentTextBox")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 301, 51))
        self.label_2.setObjectName("label_2")
        self.AllocateButton = QtWidgets.QPushButton(Form)
        self.AllocateButton.setGeometry(QtCore.QRect(40, 410, 91, 31))
        self.AllocateButton.setObjectName("AllocateButton")
        self.DeallocateButton = QtWidgets.QPushButton(Form)
        self.DeallocateButton.setGeometry(QtCore.QRect(390, 410, 91, 31))
        self.DeallocateButton.setObjectName("DeallocateButton")
        self.allProcessesMenu = QtWidgets.QComboBox(Form)
        self.allProcessesMenu.setGeometry(QtCore.QRect(390, 380, 91, 22))
        self.allProcessesMenu.setObjectName("allProcessesMenu")
        self.ProcessLabel = QtWidgets.QLabel(Form)
        self.ProcessLabel.setGeometry(QtCore.QRect(190, 20, 211, 21))
        self.ProcessLabel.setObjectName("ProcessLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Allocation Algorithm </span></p></body></html>"))
        self.radioButton_3.setText(_translate("Form", "Worst Fit"))
        self.radioButton.setText(_translate("Form", "First Fit"))
        self.radioButton_2.setText(_translate("Form", "Best Fit"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Type process segment this way: </span><span style=\" font-size:10pt; font-weight:600; color:#5d0000;\">Name:Size</span></p><p><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">Note: Separate segments by enter</span></p></body></html>"))
        self.AllocateButton.setText(_translate("Form", "Allocate"))
        self.DeallocateButton.setText(_translate("Form", "Deallocate"))
        self.ProcessLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Process Name: P1 </span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
